"""
provenance.py
The provenance contract for data/sites.json.

WHY THIS EXISTS
---------------
Before this module, a site row had exactly twelve keys (acres, city, conf,
county, lat, lon, name, owner, rank, score, state, type) and not one of them
said where the row came from or when it was screened. The map therefore
presented 463 candidate sites of unknown vintage under a README warning that
the data has "a meaningfully high chance of errors". A reader could not tell a
site screened last week from one screened last quarter, and nine of the ten
states' upstream pipelines are no longer reachable at all, so for most of the
map nobody could find out.

Provenance is tracked PER STATE, not per site row. Every row a given extractor
writes in one run shares the same source repo, source commit and extraction
date, so per-row copies would be 463 duplicates of ten facts and would bloat
the single-file index.html that embeds the payload.

as_of IS THE DATA'S DATE, NOT THE COPY'S DATE
---------------------------------------------
as_of is when the upstream pipeline last PRODUCED this data, read from the last
upstream commit that changed its outputs. extracted_on is when this repo last
copied it. The two are deliberately separate, because collapsing them defeats
the whole point: if as_of were the copy date, re-running the extractor against
an unchanged upstream would reset the clock and make months-old screening data
read as fresh. A banner built on that number would be worse than no banner.

WV is the live example. Its screening outputs were produced 2026-07-16, wired
into this map 2026-09-18, and re-verified 2026-10-04. Only the first of those
three dates tells a reader how old the screen is.

THE TWO STATUSES
----------------
live   -- the upstream pipeline is reachable and this state can be re-extracted.
          as_of is the upstream data's own date and source_commit identifies the
          exact upstream commit the CSV came from.
frozen -- the upstream pipeline is NOT reachable, so this state's data cannot be
          regenerated by anyone on this account. as_of is null, because the real
          extraction date is not recorded anywhere and inventing one would be
          worse than admitting it is unknown. What IS known is an upper bound:
          extracted_on_or_before, taken from the last commit in THIS repo that
          modified that state's file.

Never fill as_of for a frozen state with a guess, a file mtime or today's date.
An upper bound from the git record is a fact; a plausible-looking date is not.
"""
import json
import os
import subprocess

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROVENANCE_PATH = os.path.join(REPO_ROOT, 'data', 'provenance.json')

# Every key a live entry must carry. A state missing any of these is refused by
# merge_sites.py rather than merged with a hole in it.
LIVE_REQUIRED = ('source_repo', 'source_commit', 'as_of', 'extracted_on',
                 'pipeline_run', 'sites', 'status')

# A frozen entry cannot have a source_commit or an as_of, because the upstream is
# gone. It must instead carry the bound and the reason.
FROZEN_REQUIRED = ('source_repo', 'as_of', 'extracted_on_or_before', 'sites', 'status', 'note')

VALID_STATUSES = ('live', 'frozen')


def load():
    """Return the provenance map, or {} when the file does not exist yet."""
    if not os.path.exists(PROVENANCE_PATH):
        return {}
    with open(PROVENANCE_PATH) as f:
        return json.load(f)


def save(prov):
    """Write the provenance map, states in alphabetical order for a stable diff."""
    with open(PROVENANCE_PATH, 'w') as f:
        json.dump({k: prov[k] for k in sorted(prov)}, f, indent=2, sort_keys=True)
        f.write('\n')


def validate_entry(state, entry):
    """Return a list of human-readable problems with one state's entry.

    An empty list means the entry satisfies the contract. This is the single
    place that decides what a complete entry is; merge_sites.py and the tests
    both go through it so they cannot drift apart.
    """
    problems = []
    if not isinstance(entry, dict):
        return [f"{state}: provenance entry is {type(entry).__name__}, expected an object"]

    status = entry.get('status')
    if status not in VALID_STATUSES:
        problems.append(
            f"{state}: status is {status!r}, expected one of {VALID_STATUSES}")
        return problems

    required = LIVE_REQUIRED if status == 'live' else FROZEN_REQUIRED
    for key in required:
        if key not in entry:
            problems.append(f"{state}: missing required key {key!r} for status {status!r}")

    if status == 'live':
        # A live entry with a null as_of or commit is the exact hole this module
        # exists to close, so an explicit null is rejected as firmly as a
        # missing key.
        for key in ('source_commit', 'as_of', 'extracted_on', 'source_repo'):
            if key in entry and not entry[key]:
                problems.append(f"{state}: {key} is empty but status is 'live'")
    else:
        if entry.get('as_of') is not None:
            problems.append(
                f"{state}: as_of must be null for a frozen state; the real "
                f"extraction date is not recorded and must not be guessed")
        if not entry.get('extracted_on_or_before'):
            problems.append(
                f"{state}: frozen state needs extracted_on_or_before, the upper "
                f"bound from this repo's git history")

    if 'sites' in entry and not isinstance(entry['sites'], int):
        problems.append(f"{state}: sites is {entry['sites']!r}, expected an int")

    return problems


def validate(prov, states):
    """Return every problem across the named states, plus any state with no entry."""
    problems = []
    for state in states:
        if state not in prov:
            problems.append(
                f"{state}: no provenance entry. Every state must declare where "
                f"its data came from and when. See scripts/provenance.py")
            continue
        problems += validate_entry(state, prov[state])
    return problems


def git_commit(repo_dir):
    """Return repo_dir's current commit sha, or None when it is not a checkout.

    Used by an extractor to record the exact upstream commit its CSV came from.
    Returns None rather than raising so an extractor run outside a git checkout
    degrades to a reported gap instead of a crash.
    """
    try:
        out = subprocess.run(
            ['git', '-C', repo_dir, 'rev-parse', 'HEAD'],
            capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() or None


def upstream_data_date(repo_dir, data_subdir):
    """Return the date of the last commit in repo_dir that changed data_subdir.

    This is the DATA's own date: when the upstream pipeline last produced new
    output, not when this repo copied it. Returns None when repo_dir is not a
    checkout or nothing has ever touched data_subdir, so the caller reports a
    gap instead of substituting today.

    A shallow checkout will answer from the commits it happens to have, which
    is how an earlier read of this same question returned 2026-07-20 (a README
    commit, the only one in a depth-1 clone) instead of the real 2026-07-16.
    Callers that need this to be right must fetch real history first.
    """
    try:
        out = subprocess.run(
            ['git', '-C', repo_dir, 'log', '-1', '--format=%ad', '--date=short',
             '--', data_subdir],
            capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() or None


def record_live(state, source_repo, source_commit, as_of, extracted_on,
                pipeline_run, n_sites):
    """Upsert a live entry for one state and persist it.

    Called by that state's extractor at the end of a successful run, so the
    provenance is written by the same code path that writes the data and cannot
    be forgotten separately.
    """
    prov = load()
    prov[state.upper()] = {
        'status': 'live',
        'source_repo': source_repo,
        'source_commit': source_commit,
        'as_of': as_of,
        'extracted_on': extracted_on,
        'pipeline_run': pipeline_run,
        'sites': n_sites,
    }
    problems = validate_entry(state.upper(), prov[state.upper()])
    if problems:
        raise ValueError('refusing to write an invalid provenance entry:\n  '
                         + '\n  '.join(problems))
    save(prov)
    return prov[state.upper()]
